name: Generate GitHub Stats SVG (Daily)

on:
  schedule:
    - cron: "0 1 * * *"  # Daily (UTC)
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install generator
        run: |
          sudo apt-get update
          sudo apt-get install -y golang
          go install github.com/TBXark/github-status@latest

      - name: Generate SVGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          $(go env GOPATH)/bin/github-status --output generated

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated || true
          git commit -m "chore: update stats" || echo "No changes"
          git push
